export const whInit = {
  Ponedeljak: {
    date: '',
    day: 'Mon',
    morningFrom: 'nn:nn',
    morningTo: 'nn:nn',
    afternoonFrom: 'nn:nn',
    afternoonTo: 'nn:nn',
    absence: 'nema odsustva',
  },
  Utorak: {
    date: '',
    day: 'Tue',
    morningFrom: 'nn:nn',
    morningTo: 'nn:nn',
    afternoonFrom: 'nn:nn',
    afternoonTo: 'nn:nn',
    absence: 'nema odsustva',
  },
  Sreda: {
    date: '',
    day: 'Wed',
    morningFrom: 'nn:nn',
    morningTo: 'nn:nn',
    afternoonFrom: 'nn:nn',
    afternoonTo: 'nn:nn',
    absence: 'nema odsustva',
  },
  Četvrtak: {
    date: '',
    day: 'Thu',
    morningFrom: 'nn:nn',
    morningTo: 'nn:nn',
    afternoonFrom: 'nn:nn',
    afternoonTo: 'nn:nn',
    absence: 'nema odsustva',
  },
  Petak: {
    date: '',
    day: 'Fri',
    morningFrom: 'nn:nn',
    morningTo: 'nn:nn',
    afternoonFrom: 'nn:nn',
    afternoonTo: 'nn:nn',
    absence: 'nema odsustva',
  },
  Subota: {
    date: '',
    day: 'Sat',
    morningFrom: 'nn:nn',
    morningTo: 'nn:nn',
    afternoonFrom: 'nn:nn',
    afternoonTo: 'nn:nn',
    absence: 'nema odsustva',
  },
  Nedelja: {
    date: '',
    day: 'Sun',
    morningFrom: 'nn:nn',
    morningTo: 'nn:nn',
    afternoonFrom: 'nn:nn',
    afternoonTo: 'nn:nn',
    absence: 'nema odsustva',
  },
};
