export const WorkingHoursInit = [
  {
    date: '',
    day: 'Mon',
    morningFrom: 'nn:nn',
    morningTo: 'nn:nn',
    afternoonFrom: 'nn:nn',
    afternoonTo: 'nn:nn',
    absence: 'nema odsustva',
  },
  {
    date: '',
    day: 'Tue',
    morningFrom: 'nn:nn',
    morningTo: 'nn:nn',
    afternoonFrom: 'nn:nn',
    afternoonTo: 'nn:nn',
    absence: 'nema odsustva',
  },
  {
    date: '',
    day: 'Wed',
    morningFrom: 'nn:nn',
    morningTo: 'nn:nn',
    afternoonFrom: 'nn:nn',
    afternoonTo: 'nn:nn',
    absence: 'nema odsustva',
  },
  {
    date: '',
    day: 'Thu',
    morningFrom: 'nn:nn',
    morningTo: 'nn:nn',
    afternoonFrom: 'nn:nn',
    afternoonTo: 'nn:nn',
    absence: 'nema odsustva',
  },
  {
    date: '',
    day: 'Fri',
    morningFrom: 'nn:nn',
    morningTo: 'nn:nn',
    afternoonFrom: 'nn:nn',
    afternoonTo: 'nn:nn',
    absence: 'nema odsustva',
  },
  {
    date: '',
    day: 'Sat',
    morningFrom: 'nn:nn',
    morningTo: 'nn:nn',
    afternoonFrom: 'nn:nn',
    afternoonTo: 'nn:nn',
    absence: 'nema odsustva',
  },
  {
    date: '',
    day: 'Sun',
    morningFrom: 'nn:nn',
    morningTo: 'nn:nn',
    afternoonFrom: 'nn:nn',
    afternoonTo: 'nn:nn',
    absence: 'nema odsustva',
  },
];
